styleの修正
prog-g/dcc-report pull request #45
Opened 2020-05-28 11:11 UTC by hatosh

Note, graphに影をつける
枠線を2pxから1pxへ
Note,graphの灰色の背景色を#f7f7ffに変更

2020-05-28 11:56 UTC, ahuglajbclajep commented
変更後の画像お願いします！

2020-06-11 04:08 UTC, ahuglajbclajep commented
`npm run start` が効かなかったので rebase した ✔️

2020-09-13 08:01 UTC, ahuglajbclajep commented
とりあえずコンフリクトを解消したのでレビューします。

2020-09-13 09:08 UTC, ahuglajbclajep requested changes

2020-09-13 09:08 UTC, ahuglajbclajep commented on src/index.ejs
> +      href="https://fonts.googleapis.com/css2?family=Anton&display=swap"
Googleフォントは使用する文字だけを指定して最適化できるので、以下のように `text=` を指定してください。
https://developers.google.com/fonts/docs/getting_started#optimizing_your_font_requests

```suggestion
      href="https://fonts.googleapis.com/css2?family=Anton&display=swap&text=DCReport%3An%2Fa1234567.%2C%23xyN%2BAdI%26m"
```

ちなみに `text=` 以降の文字列は `encodeURIComponent([...new Set("DCCReport:n/a1234567.,#xyNote+AddID&Name")].join(""))` などのようにすると得られます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

あと個人的には結構フォント太いなと思いました。
もう少し選定してもいいかも。

2020-09-13 09:08 UTC, ahuglajbclajep commented on src/index.ejs
> +      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
今はまだいいですが、アイコンも特定のものしか読み込まないので、`all.min.css` を指定するのはあまりよくない気がします。
https://fontawesome.com/how-to-use/on-the-web/other-topics/performance

2020-09-13 09:43 UTC, ahuglajbclajep commented
本題からは逸れるけど、スマホ向けなので開始値とか終了値のところは二段にしないほうが見栄えいいかもですね……

2020-10-14 13:32 UTC, ahuglajbclajep requested changes
だいたいいい感じだと思います。
ただアイコンに関しては、今以上に情報を減らすと何をするボタンなのかわからないと思うので、なんだかんだ入れない方が良かったかもですね……。
何度も申し訳ないですが、このPRはそのままでよいのでアイコン以外の変更を別のPRとして出してもらってもよいですか？
あと新しいPRのほうで追加で指摘したCSSの変更もやってもらえると助かります 🙏

2020-10-14 13:32 UTC, ahuglajbclajep commented on src/style.css
> +  border-radius: 6px 6px;
`border-radius: 6px;` でよさそう

2020-10-14 13:32 UTC, ahuglajbclajep commented on src/style.css
> +  box-shadow: 8px 8px 5px #aaa;
`box-shadow: 8px 8px 8px #aaa;` とかが良い感じ？

2020-10-14 13:32 UTC, ahuglajbclajep commented on src/style.css
> +  border-radius: 6px 0 0 0;
`border-top-left-radius: 6px;`

2020-10-14 13:32 UTC, ahuglajbclajep commented on src/style.css
> +  box-shadow: 8px 8px 5px #bbb;
`box-shadow: 8px 8px 8px #aaa;` とかが良い感じ？

2020-10-15 07:13 UTC, curegit commented on src/style.css
> +  box-shadow: 8px 8px 5px #aaa;
影が主張しすぎてて、下のメモとかにくっつくぐらい広いので `2px 2px 8px #aaa` ぐらいでいいと思いました。

2020-10-15 07:15 UTC, curegit commented on src/style.css
> +  box-shadow: 8px 8px 5px #bbb;
影が主張しすぎてて、下のメモとかにくっつくぐらい広いので `2px 2px 8px #bbb` ぐらいでいいと思いました。

2020-10-15 07:22 UTC, curegit commented
graph の影ですがの、値によっては上側の境界の表示に影響が出ちゃうようです（Chrome mac）
`4px 4px 5px` の場合：

![image](https://user-images.githubusercontent.com/37978051/96089764-43fdf480-0f02-11eb-8774-d22463b92449.png)

2020-10-15 07:34 UTC, curegit requested changes
ボタンのラベルを `i` 要素でマークアップするのは変だと思いました。

2020-11-05 15:27 UTC, closed without merging