renovateの設定にstabilityDaysを追加した (#78)
prog-g/dcc-report pull request #97
Opened 2020-09-29 10:38 UTC by kurokoji

## やったこと

- renovateの設定に `stabilityDays` を追加した

## 関連する issue や PR やドキュメント
#78 

## 備考

2020-10-03 13:41 UTC, ahuglajbclajep requested changes
#87 に書いたようにブランチの保護を有効にしていると `:automergePatch` が効かなくなるので、patch についても minor と同様に週1での更新にまとめてしまいたいと思っています。
これは以下の追加の設定を参考に書いてもらえばいいかなと思います。
https://github.com/ahuglajbclajep/renovate-config/tree/140bc1c#usage

また `stabilityDays` を設定する場合は `:unpublishSafe` は不要ですが、`:dependencyDashboard` は追加してほしいです。
https://docs.renovatebot.com/configuration-options/#stabilitydays

2020-10-03 13:47 UTC, ahuglajbclajep commented
Slack の PR 作ったよ通知がうるさめなので早めに着手してもらえると助かります 🙏

2020-10-13 09:04 UTC, kurokoji commented
> 
> 
> #87 に書いたようにブランチの保護を有効にしていると `:automergePatch` が効かなくなるので、patch についても minor と同様に週1での更新にまとめてしまいたいと思っています。
> これは以下の追加の設定を参考に書いてもらえばいいかなと思います。
> https://github.com/ahuglajbclajep/renovate-config/tree/140bc1c#usage
> 
> また `stabilityDays` を設定する場合は `:unpublishSafe` は不要ですが、`:dependencyDashboard` は追加してほしいです。
> https://docs.renovatebot.com/configuration-options/#stabilitydays

@ahuglajbclajep commitしたのでレビューのほうお願いします!!

2020-10-13 10:52 UTC, ahuglajbclajep commented
`"updateTypes": ["patch"]` のときは `dependencies` と `devDependencies` は分けなくてよいです。
それ以外はよさそう。

2020-10-13 11:16 UTC, kurokoji commented
@ahuglajbclajep 修正しました

2020-10-13 11:40 UTC, ahuglajbclajep approved these changes
`npx -qp renovate -c renovate-config-validator` も通ったのでマージします！
ありがとう。

2020-10-13 11:40 UTC, merged